name: NT_analysis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - nibabel
  - nilearn
  - scikit-learn
  - statsmodels
  - openpyxl
  - pyyaml
  - requests
  - datalad
  - matplotlib
  - seaborn
  - tqdm
  - jupyter
  - nbconvert
  - ipykernel
  - pytest
  - pip:
      - xlrd
      - datalad-osf
