project_dir = '/home/zhenzong2/analysis/neurotransmitter';
addpath(genpath(fullfile(project_dir, 'external', 'niistat')));
spm('Defaults', 'fmri');

% 运行节点级NiiStat核心分析
node_input = fullfile(project_dir, 'derivatives', 'node_clsm', 'dat_node_niistat_input.mat');
node_output = fullfile(project_dir, 'derivatives', 'node_clsm', 'niistat_node_results');
if ~exist(node_output, 'dir')
    mkdir(node_output);
end
cd(node_output);
node_data = load(node_input);
node_hdr = spm_vol(fullfile(project_dir, 'atlases', 'processed', 'atlas4s156_2mm.nii.gz'));
node_roi_names = reshape(cellstr(node_data.roi_names), [], 1);
nii_stat_core( ...
    node_data.les, ...
    node_data.beh, ...
    cellstr(node_data.beh_names), ...
    node_hdr, ...
    0.05, ...
    -1, ...
    logical(node_data.logical_mask), ...
    'dat_node_clsm', ...
    node_roi_names, ...
    [], ...
    node_data.nuisance);

% 运行DAT-WM voxelwise NiiStat核心分析
wm_input = fullfile(project_dir, 'derivatives', 'wm_voxel_clsm', 'dat_wm_voxel_niistat_input.mat');
wm_output = fullfile(project_dir, 'derivatives', 'wm_voxel_clsm', 'niistat_wm_results');
if ~exist(wm_output, 'dir')
    mkdir(wm_output);
end
cd(wm_output);
wm_data = load(wm_input);
wm_hdr = spm_vol(fullfile(project_dir, 'atlases', 'processed', 'dat_wm_mask_2mm.nii.gz'));
nii_stat_core( ...
    wm_data.les, ...
    wm_data.beh, ...
    cellstr(wm_data.beh_names), ...
    wm_hdr, ...
    0.05, ...
    -1, ...
    logical(wm_data.logical_mask), ...
    'dat_wm_voxel_clsm', ...
    {}, ...
    [], ...
    wm_data.nuisance);

cd(project_dir);
