project_dir = getenv('NT_PROJECT_DIR');
niistat_repo = getenv('NT_NIISTAT_REPO');
node_input = getenv('NT_NODE_INPUT');
node_output = getenv('NT_NODE_OUTPUT');
node_hdr_path = getenv('NT_NODE_HDR');
wm_input = getenv('NT_WM_INPUT');
wm_output = getenv('NT_WM_OUTPUT');
wm_hdr_path = getenv('NT_WM_HDR');
p_thresh = str2double(getenv('NT_P_THRESH'));
num_permute = str2double(getenv('NT_NUM_PERMUTE'));
if isempty(project_dir)
    project_dir = pwd;
end
if isnan(p_thresh)
    p_thresh = 0.05;
end
if isnan(num_permute)
    num_permute = -1;
end

addpath(genpath(niistat_repo));
spm('Defaults', 'fmri');

% 运行节点级NiiStat核心分析
if ~exist(node_output, 'dir')
    mkdir(node_output);
end
cd(node_output);
node_data = load(node_input);
node_hdr = spm_vol(node_hdr_path);
node_roi_names = reshape(cellstr(node_data.roi_names), [], 1);
nii_stat_core( ...
    node_data.les, ...
    node_data.beh, ...
    cellstr(node_data.beh_names), ...
    node_hdr, ...
    p_thresh, ...
    num_permute, ...
    logical(node_data.logical_mask), ...
    'dat_node_clsm', ...
    node_roi_names, ...
    [], ...
    node_data.nuisance);

% 运行DAT-WM voxelwise NiiStat核心分析
if ~exist(wm_output, 'dir')
    mkdir(wm_output);
end
cd(wm_output);
wm_data = load(wm_input);
wm_hdr = spm_vol(wm_hdr_path);
nii_stat_core( ...
    wm_data.les, ...
    wm_data.beh, ...
    cellstr(wm_data.beh_names), ...
    wm_hdr, ...
    p_thresh, ...
    num_permute, ...
    logical(wm_data.logical_mask), ...
    'dat_wm_voxel_clsm', ...
    {}, ...
    [], ...
    wm_data.nuisance);

cd(project_dir);
